psql -c "CREATE USER drupal_admin81 WITH ENCRYPTED PASSWORD 'hola123.,' NOCREATEDB;"
psql -c "CREATE USER drupal_admin82 WITH ENCRYPTED PASSWORD 'hola123.,' NOCREATEDB;"
psql -c "CREATE DATABASE drupal81 WITH OWNER=drupal_admin81 ENCODING=UTF8"
psql -c "CREATE DATABASE drupal82 WITH OWNER=drupal_admin82 ENCODING=UTF8"